### ISSUE TITLE
Modified date not updating in files

### ISSUE THREAD

**Issue by gerardoglz** [daschuer/nemo#1]
I'm using Using Ubuntu 14.04. I recently found out that when opening/reloading a folder, the date of the last modification of a file is not being correctly updated in the Modified column, when using the format: "today at 00:00:00". 

For example, today Friday I opened a folder in which some files were created yesterday (Thursday) at 2:00pm. When I created them yesterday, they correctly indicated that they were modified 'today at 14:00'.

Today those files should appear as being last modified 'yesterday at 14:00', however they are still being displayed as last modified 'today at 14:00'. 

Let me know if you need further info.
Thanks!

**Comment by daschuer** [comment]
Thank you for the report. I can confirm this. 

It is already fixed upstream here: 
https://github.com/GNOME/nautilus/commit/91d5990612fdeebb080fb2c55f1740bfc2c64ef2

Original Nemo is effected as well: 
https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-file.c#L4584

**Comment by daschuer** [comment]
Fixed in nemo 3.2.2.38-daschuer
https://github.com/daschuer/nemo/commit/35ceed2825f1a8ec49a774e20ff0579b90f6491b
